server:
  port: 8080
spring:
  application:
    name: swine-search-project
  servlet:
    multipart:
      max-file-size: 10000000000
  mvc:
    servlet:
      load-on-startup: 1
  datasource:
    dynamic:
      primary: private
      strict: false
      p6spy: true
      druid:
        keepAlive: true
        initial-size: 4
        min-idle: 4
        maxActive: 30
        maxWait: 60000
        minEvictableIdleTimeMillis: 60000
        validationQuery: SELECT 1 FROM DUAL
        testOnBorrow: false
        test-on-return: false
        testWhileIdle: true
        poolPreparedStatements: true
        share-prepared-statements: true
        maxPoolPreparedStatementPerConnectionSize: 100
      datasource:
        private:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://162.14.75.32:3306/cotton
          username: root
          password: dd20021120
springdoc:
  api-docs:
    enabled: true
    path: /docs
  packages-to-scan: com.example.swinedatebaseproject.controller
  paths-to-match: /orthogroups5genomesPlus/**
  swagger-ui:
    enabled: true
    path: /docs-ui
mybatis-plus:
  global-config:
    banner: false