spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://gz-cynosdbmysql-grp-lqdbgset.sql.tencentcdb.com:23453/cotton
    username: root
    password: Du061224
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      # 默认排除静态资源

server:
  port: 8080
springdoc:
  packages-to-scan: swine_search.controller
  swagger-ui:
    # 修改Swagger UI路径
    # /api-docs->/swagger-ui/index.html
    path: /api-docs
    # 开启Swagger UI界面
    enabled: true
  api-docs:
    # 修改api-docs路径
    path: /v3/api-docs
    # 开启api-docs
    enabled: true
    # 配置需要生成接口文档的接口路径
    # paths-to-match: /cds/**